#!/usr/bin/env python3
"""Render the machine-readable genealogy as deterministic Markdown."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GENEALOGY = ROOT / "genealogy"
OUTPUT = GENEALOGY / "generated" / "GENEALOGY.md"


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def yes_no(value: bool) -> str:
    return "yes" if value else "no"


def link(text: str, url: str) -> str:
    return f"[{escape(text)}]({url})"


def render() -> str:
    nodes = load_jsonl(GENEALOGY / "benchmark_nodes_v0.1.jsonl")
    edges = load_jsonl(GENEALOGY / "benchmark_edges_v0.1.jsonl")
    collaborations = sorted(
        load_jsonl(GENEALOGY / "collaboration_targets_v0.1.jsonl"),
        key=lambda row: row["priority"],
    )
    candidates = load_jsonl(GENEALOGY / "candidates" / "latest.jsonl")
    profile = json.loads((GENEALOGY / "portsmouth_portfolio_profile_v0.1.json").read_text(encoding="utf-8"))

    by_id = {node["id"]: node for node in nodes}
    checked = max(node["latest_checked"] for node in nodes)
    kind_counts = Counter(node["kind"] for node in nodes)
    status_counts = Counter(node["status"] for node in nodes)

    lines: list[str] = [
        "<!-- Generated by scripts/render_genealogy.py. Edit the JSON/JSONL sources, not this file. -->",
        "",
        "# Living AI-research benchmark genealogy",
        "",
        f"**Evidence checked:** {checked}",
        "",
        f"The curated graph contains **{len(nodes)} nodes**, **{len(edges)} relationships** and "
        f"**{len(collaborations)} collaboration targets**. The discovery queue contains "
        f"**{len(candidates)} candidate records**.",
        "",
        "## Portsmouth research production function",
        "",
        "The Portsmouth programme extends BMA-ARB from autonomous capability measurement to a costed research production function. "
        "It will estimate the number of journal-ready outputs produced by combinations of human effort, compute, orchestration and verification, "
        "weighted to Portsmouth's observed business and management portfolio. Released academic time is a resource benefit. "
        "Owned GPUs remain an optional comparator rather than a presumed requirement.",
        "",
        "### Contribution boundary",
        "",
        "| Existing capability | Closest prior work | Portsmouth addition |",
        "| --- | --- | --- |",
        "| Autonomous public-data social-science papers | Project APE | Blinded journal-readiness review, academic-time logging and actual-portfolio weighting |",
        "| Costed defect detection in executable papers | CRED | Business and management validity domains plus total production and rework cost |",
        "| Progressive removal of human guidance | ASI-Bench | Price each guidance condition and retain journal-ready output as the outcome |",
        "| End-to-end social-science replication | ReplicatorBench and SocSci-Repro-Bench | Production of new articles and substitution at research-work-package level |",
        "| Scientific induction under hidden rules | Science Sandboxes and DiscoverPhysics | Organisational dry/damp worlds linked to real paper-production trials |",
        "| Research-compute allocation | AI Research Preference Models | Minimise resource cost per journal-ready business and management output |",
        "| Economically valuable agent work | Agents' Last Exam | University research production, released academic capacity and infrastructure choice |",
        "",
        "## Portfolio evidence currently available",
        "",
        f"The privacy-safe profile contains **{profile['candidate_output_count']}** candidate UOA17 outputs. "
        f"Journal enrichment status is **{profile['journal_portfolio_status'].replace('_', ' ')}**. "
        "Title signals overlap and are used only as provisional coverage checks.",
        "",
        "| Title-level signal | Outputs | Share |",
        "| --- | ---: | ---: |",
    ]
    for row in profile["title_signal_counts"]:
        lines.append(
            f"| {escape(row['signal'].replace('_', ' '))} | {row['count']} | {row['percent_of_outputs']:.1f}% |"
        )

    lines.extend(
        [
            "",
            "The current source does not contain journal title or ISSN. The production benchmark will therefore remain unweighted by journal "
            "until an authorised public-metadata join is completed. It must not infer CABS or journal tiers from titles.",
            "",
            "## Collaboration route",
            "",
            "| Priority | Target | Proposed joint work | First contact objective |",
            "| ---: | --- | --- | --- |",
        ]
    )
    for row in collaborations:
        node = by_id[row["target_id"]]
        lines.append(
            f"| {row['priority']} | {link(node['name'], row['source_url'])} | "
            f"{escape(row['proposal'])} | {escape(row['first_contact_goal'])} |"
        )

    lines.extend(
        [
            "",
            "## Key relationship graph",
            "",
            "```mermaid",
            "graph LR",
        ]
    )
    focus_ids = {
        "portsmouth_rpf",
        "bma_arb",
        "project_ape",
        "cred",
        "replicatorbench",
        "socsci_repro_bench",
        "asi_bench",
        "science_sandboxes",
        "research_preference_models",
        "qworld",
        "autoresearchclaw",
        "oragentbench",
        "agents_last_exam",
        "closing_loop_review",
        "ai_scientists_results_without_reasoning",
        "s_researcher",
        "arbor_htr",
    }
    short_labels = {
        "portsmouth_rpf": "Portsmouth RPF",
        "bma_arb": "BMA-ARB",
        "project_ape": "Project APE",
        "cred": "CRED",
        "replicatorbench": "ReplicatorBench",
        "socsci_repro_bench": "SocSci-Repro-Bench",
        "asi_bench": "ASI-Bench",
        "science_sandboxes": "Science Sandboxes",
        "research_preference_models": "Research Preference Models",
        "qworld": "Qworld",
        "autoresearchclaw": "AutoResearchClaw",
        "oragentbench": "ORAgentBench",
        "agents_last_exam": "Agents' Last Exam",
        "closing_loop_review": "Closing the Loop",
        "ai_scientists_results_without_reasoning": "Results without scientific reasoning",
        "s_researcher": "S-Researcher",
        "arbor_htr": "Arbor HTR",
    }
    for node_id in sorted(focus_ids):
        label = short_labels[node_id].replace('"', "'")
        shape_left, shape_right = ("[[", "]]" ) if node_id in {"portsmouth_rpf", "bma_arb"} else ("[", "]")
        lines.append(f'  {node_id}{shape_left}"{label}"{shape_right}')
    for edge in edges:
        if edge["from"] in focus_ids and edge["to"] in focus_ids:
            relation = edge["relation"].replace("_", " ")
            lines.append(f'  {edge["from"]} -->|"{relation}"| {edge["to"]}')
    lines.extend(["```", ""])

    lines.extend(
        [
            "## Curated registry",
            "",
            "| Work | Year | Kind | Evaluation unit | Human guidance | Human time reported | Monetary cost reported | Journal floor | Portsmouth relevance |",
            "| --- | ---: | --- | --- | --- | --- | --- | --- | ---: |",
        ]
    )
    for node in sorted(nodes, key=lambda row: (-row["portsmouth_relevance"], row["year"], row["name"].lower())):
        lines.append(
            f"| {link(node['name'], node['source_url'])} | {node['year']} | {escape(node['kind'])} | "
            f"{escape(node['evaluation_unit'].replace('_', ' '))} | "
            f"{escape(node['human_guidance'].replace('_', ' '))} | "
            f"{yes_no(node['reports_human_time'])} | {yes_no(node['reports_monetary_cost'])} | "
            f"{yes_no(node['journal_quality_floor'])} | {node['portsmouth_relevance']} |"
        )

    lines.extend(
        [
            "",
            "## Registry composition",
            "",
            "| Dimension | Counts |",
            "| --- | --- |",
            "| Kind | " + ", ".join(f"{key}: {value}" for key, value in sorted(kind_counts.items())) + " |",
            "| Status | " + ", ".join(f"{key}: {value}" for key, value in sorted(status_counts.items())) + " |",
            "",
            "## Candidate queue",
            "",
        ]
    )
    if not candidates:
        lines.append("No automatically discovered candidates are awaiting review.")
    else:
        lines.extend(
            [
                "| Candidate | Published | Matched searches | Review status |",
                "| --- | --- | --- | --- |",
            ]
        )
        for row in sorted(candidates, key=lambda item: (item["published"], item["title"]), reverse=True)[:50]:
            lines.append(
                f"| {link(row['title'], row['source_url'])} | {escape(row['published'])} | "
                f"{escape(', '.join(row['search_terms']))} | {escape(row['review_status'])} |"
            )

    lines.extend(
        [
            "",
            "## Maintenance rule",
            "",
            "Automated discovery can append candidates but cannot amend curated nodes or relationships. "
            "Promotion requires review of a primary source, a claim boundary and at least one supported relationship. "
            "Historic records are versioned rather than silently overwritten.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if the generated file is stale.")
    parser.add_argument("--output", default=str(OUTPUT))
    args = parser.parse_args()

    output = Path(args.output)
    content = render()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != content:
            print(f"{output.relative_to(ROOT)} is stale; run scripts/render_genealogy.py", file=sys.stderr)
            return 1
        print(f"{output.relative_to(ROOT)} is current")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
